{{alias}}
direct      = +forward-override{forward .}
shadowsocks         = +forward-override{forward-socks5 127.0.0.1:1080 .}
default     = direct
#==========默认代理==========
{default}
/
#==========直接连接==========
{direct} 
.edu.cn
202.117.255.
222.24.211.70
#==========shadowsocks代理==========
{shadowsocks}
com.google
domains.google
googleapis.com
googleapps.com
googleartproject.com
googleblog.com
googlebot.com
googlecode.com
googlecommerce.com
googledomains.com
googledrive.com
googleearth.com
googlegroups.com
googlehosted.com
googleideas.com
googlelabs.com
googlemail.com
googleplay.com
googleplus.com
googlesource.com
googleusercontent.com
googlevideo.com
googlezip.net
groups.google.cn
gstatic.com
.google.com
.googlesile.com
.git.io
.github.com
.0rz.tw
.1000giri.net
.100ke.org
.10conditionsoflove.com
.12bet.com
.12vpn.com
.12vpn.net
.141tube.com
.1688.com.au
.173ng.com
.177pic.info
.17t17p.com
.18virginsex.com
.1949er.org
.1984bbs.org
.1998cdp.org
.1bao.org
.1eew.com
.1mobile.com
.2000fun.com/bbs
.2008xianzhang.info
.21pron.com
.228.net.tw
.2-hand.info
.2shared.com
.315lz.com
.3a5a.com
.3boys2girls.com
.3d-game.com
.3ren.ca
.3tui.net
.4everproxy.com
.4irc.com
.51luoben.com
.5isotoi5.org
.5maodang.com
.64museum.org
.66.ca
.7cow.com
.881903.com/page/zh-tw/
.888.com
.888poker.com
.8-d.com
.8news.com.tw
.8z1.net
.9001700.com
.92ccav.com
.991.com
.99btgc01.com
.99cn.info
.abc.com
.abchinese.com
.ablwang.com
.aboluowang.com
.aboutgfw.com
.abs.edu
.accim.org
.aceros-de-hispania.com
.acevpn.com
.acg18.me
.adpl.org.hk
.adult-sex-games.com
.ae.org
.afantibbs.com
.ai-kan.net
.aiph.net
.airvpn.org
.aisex.com
.aiweiweiblog.com
.akademiye.org/ug
.alanhou.com
.alhayat.com
.alldrawnsex.com
.allinfa.com
.alljackpotscasino.com
.alphaporno.com
.alwaysvpn.com
.amigobbs.net
.amitabhafoundation.us
.amnesty.org
.amnesty.tw
.amnestyusa.org
.amnyemachen.org
.amoiist.com
.animeshippuuden.com
.anonymitynetwork.com
.anonymizer.com
.anpopo.com
.answering-islam.org
.antiwave.net
.anysex.com
.aofriend.com
.aofriend.com.au
.aojiao.org
.apetube.com
.apigee.com
.appdownloader.net/Android
.appspot.com
.arctosia.com
.arethusa.su
.art4tibet1998.org
.asahichinese.com
.asiaharvest.org
.asiatgp.com
.askynz.net
.atchinese.com
.atlaspost.com
.atnext.com
.avcity.tv
.avcool.com
.avdb.in
.avdb.tv
.avfantasy.com
.avmo.pw
.avmoo.com
.avmoo.net
.avyahoo.com
.azerbaycan.tv
.b0ne.com
.backpackers.com.tw/forum
.badjojo.com
.banana-vpn.com
.bangchen.net
.bannednews.org
.barenakedislam.com
.bbc.co*zhongwen
.bbc.co.uk*chinese
.bbc.co.uk/news/world-asia-china
.bbc.co.uk/tv
.bbcchinese.com
.bbg.gov
.bbnradio.org
.bbsdigest.com/thread
.bbsmo.com
.bbsone.com
.bcast.co.nz
.bcc.com.tw/board
.bcchinese.net
.bcmorning.com
.beaconevents.com
.bebo.com
.beevpn.com
.behindkink.com
.belamionline.com
.berlintwitterwall.com
.berm.co.nz
.bestforchina.org
.bestvpnserver.com
.bestvpnservice.com
.bestvpnusa.com
.beta.iset.com.tw/forum
.betfair.com
.bettervpn.com
.bettween.com
.bewww.net
.beyondfirewall.com
.bgvpn.com
.biblesforamerica.org
.bic2011.org
.bignews.org
.bigsound.org
.bit.do
.bit.ly
.bitshare.com
.bjnewlife.org
.blacklogic.com
.blackvpn.com
.blinkx.com
.blip.tv
.blockcn.com
.blogcatalog.com
.blogger.com
.bloglines.com
.blogtd.org
.bloomberg.cn
.bloomberg.com
.bmfinn.com
.bod.asia
.bodog88.com
.bolehvpn.net
.bonbonsex.com
.bongacams.com
.bot.nu
.bowenpress.com
.boxpn.com
.boxun.tv
.boxunclub.com
.boyfriendtv.com
.boysfood.com
.brainyquote.com/quotes/authors/d/dalai_lama
.bravotube.net
.brazzers.com
.break.com
.breakingtweets.com
.briefdream.com/%E7%B4%A0%E6%A3%BA
.broadpressinc.com
.brutaltgp.com
.btku.me
.btspread.com
.budaedu.org
.buddhistchannel.tv
.buffered.com
.bullog.org
.bullogger.com
.busayari.com
.businessinsider.com/bing-could-be-censoring-search-results-2014
.businessinsider.com/china-banks-preparing-for-debt-implosion-2014
.businessinsider.com/hong-kong-activists-defy-police-tear-gas-as-protests-continue-overnight-2014
.businessinsider.com/internet-outages-reported-in-north-korea-2014
.businessinsider.com/iphone-6-is-approved-for-sale-in-china-2014
.businessinsider.com/nfl-announcers-surface-tablets-2014
.businessinsider.com/umbrella-man-hong-kong-2014
.businessweek.com
.busu.org/news
.buugaa.com
.buzzhand.com
.buzzhand.net
.c100tibet.org
.cachinese.com
.cacnw.com
.cactusvpn.com
.cafepress.com
.cahr.org.tw
.calameo.com/books
.calgarychinese.ca
.calgarychinese.com
.calgarychinese.net
.cam4.com
.cam4.jp
.cam4.sg
.camfrog.com
.cams.org.sg
.canyu.org
.cao.im
.caobian.info
.cap.org.hk
.carabinasypistolas.com
.cartoonmovement.com
.casadeltibetbcn.org
.casatibet.org.mx
.casinobellini.com
.casinoking.com
.casinoriva.com
.catholic.org.hk
.cathvoice.org.tw
.cbc.ca
.cbsnews.com/video
.cbtc.org.hk
.ccdtr.org
.cchere.com
.ccim.org
.cclife.ca
.ccthere.com
.cctongbao.com/article/2078732
.ccvoice.ca
.ccw.org.tw
.cdef.org
.cdnews.com.tw
.cdpa.url.tw
.cecc.gov
.centurys.net
.cfhks.org.hk
.cftfc.com
.cgdepot.org
.cgst.edu
.change.org
.changp.com
.changsa.net
.chapm25.com
.chatnook.com
.chaturbate.com
.chenguangcheng.com
.chenpokong.com
.chenpokong.net
.chhongbi.org
.china5000.us
.chinacitynews.be
.chinadialogue.net
.chinadigitaltimes.net
.chinaelections.org
.chinaeweekly.com
.chinagate.com
.chinagreenparty.org
.chinahorizon.org
.chinahush.com
.chinainperspective.com
.chinainperspective.org
.china-mmm.net
.chinamule.com
.chinapost.com.tw/taiwan/national/national-news
.chinapress.com.my
.chinarightsia.org
.chinasucks.net
.chinatimes.com/realtimenews/260409/
.chinatown.com.au
.china-week.com
.chinaworker.info
.chinesedaily.com
.chinesedemocracy.com
.chinese-hermit.net
.chinesen.de
.chinesepen.org
.chinesetalks.net/ch
.chingcheong.com
.chinman.net
.chrdnet.com
.christianfreedom.org
.chrlawyers.hk
.chuang-yen.org
.churchinhongkong.org/b5/index.php
.cineastentreff.de
.cipfg.org
.citizenlab.org
.city365.ca
.citytalk.tw/event
.civicparty.hk
.civiliangunner.com
.civilmedia.tw
.ck101.com
.clarionproject.org/news/islamic-state-isis-isil-propaganda
.clb.org.hk
.clipfish.de
.cn.sandscotaicentral.com
.cn6.eu
.cnabc.com
.cnd.org
.cnex.org.cn
.cnineu.com
.cnn.com/video
.cnpolitics.org
.cnproxy.com
.cn-proxy.com
.cochina.co
.code1984.com/64
.comic-mega.me
.communistcrimes.org
.contactmagazine.net
.convio.net
.coobay.com
.coolaler.com
.coolncute.com
.cos-moe.com
.creadersnet.com
.crocotube.com
.crossthewall.net
.c-spanvideo.org
.ctao.org
.ctfriend.net
.ctitv.com.tw
.cuhkacs.org/~benng
.cuihua.org
.cuiweiping.net
.cumlouder.com
.cusu.hk
.cw.com.tw
.d100.net
.d2bay.com
.dabr.co.uk
.dadi360.com
.daidostup.ru
.dailidaili.com
.dailymotion.com
.dajiyuan.com
.dalailama.mn
.dalailama.ru
.dalailama-archives.org
.dalailamacenter.org
.dalailamafilm.com
.dalailamafoundation.org
.dalailamahindi.com
.dalailamainaustralia.org
.dalailamajapanese.com
.dalailamaprotesters.info
.dalailamaquotes.org
.dalailamatrust.org
.dalailamavisit.org.nz
.dalailamaworld.com
.daliulian.org
.danke4china.net
.danwei.org
.darktech.org
.david-kilgour.com
.daylife.com/topic/dalai_lama
.dbc.hk/main
.ddc.com.tw
.ddhw.info
.ddns.ms
.deaftone.com
.definebabe.com
.democrats.org
.de-sci.org
.destroy-china.jp
.dharamsalanet.com
.diaoyuislands.org
.diigo.com
.dipity.com
.discuss.com.hk
.discuss4u.com
.disqus.com
.dit-inc.us
.dizhidizhi.com
.djorz.com
.dnscrypt.org
.dogfartnetwork.com/tour
.dojin.com
.dok-forum.net
.domain.club.tw
.domaintoday.com.au
.dongtaiwang.net
.dongyangjing.com
.dontfilter.us
.dorjeshugden.com
.dotplane.com
.drepung.org
.drmingxia.org
.drtuber.com
.dscn.info
.dstk.dk
.dtdns.net
.dtwang.org
.duckdns.org
.duckduckgo.com
.duckload.com/download
.duga.jp
.duihua.org
.duoweitimes.com
.dushi.ca
.dw.com
.dw-world.com
.dw-world.de
.dyndns.org
.dzze.com
.e123.hk
.earlytibet.com
.earthcam.com
.earthvpn.com
.easternlightning.org
.eastturkestan.com
.eastturkistancc.org
.eastturkistan-gov.org
.eastturkistangovernmentinexile.us
.easyca.ca
.easypic.com
.ebony-beauty.com
.economist.com
.edmontonchina.cn
.edmontonservice.com
.edubridge.com
.edupro.org
.effers.com
.efukt.com
.e-gold.com
.eisbb.com
.eksisozluk.com
.eltondisney.com
.emaga.com/info/3407
.embr.in
.empfil.com
.emule-ed2k.com
.emulefans.com
.emuparadise.me
.enfal.de
.enlighten.org.tw
.entnt.com
.episcopalchurch.org
.epochhk.com
.epochtimes.cz
.epochtimes.ie
.epochtimes.it
.epochweek.com
.eporner.com
.equinenow.com
.eraysoft.com.tr
.erepublik.com
.erights.net
.erktv.com
.eromon.net
.eroprofile.com
.eroticsaloon.net
.eslite.com/product
.eslite.com/Search_BW.aspx?q
.etaa.org.au
.etowns.net
.etowns.org
.e-traderland.net/board
.ettoday.net
.eu.org
.eucasino.com
.eulam.com
.evschool.net
.exchristian.hk
.expekt.com
.expressvpn.com
.extmatrix.com
.extremetube.com
.eyny.com
.e-zone.com.hk/discuz
.ezpc.tk/category/soft
.ezpeer.com
.facebook.com
.faceless.me
.faith100.org
.faithfuleye.com
.fakku.net
.falsefire.com
.falungong.de
.falunpilipinas.net
.fangbinxing.com
.fangmincn.org
.fan-qiang.com
.fanqiang.tk
.fanyue.info
.farwestchina.com
.fawanghuihui.org
.fc2china.com
.fc2cn.com
.fdc89.jp
.feifeiss.com
.feitian-california.org
.fengzhenghu.com
.fengzhenghu.net
.fevernet.com
.fgmtv.org
.fhreports.net
.fileflyer.com
.files2me.com
.fileserve.com/file
.filthdump.com
.finchvpn.com
.fingerdaily.com
.firefoxfan.cc
.fireofliberty.org
.firetweet.io
.flagsonline.it
.fleursdeslettres.com
.fling.com
.flnet.org
.fochk.org
.focusvpn.com
.fofg-europe.net
.fooooo.com
.forum4hk.com
.fpmt.org
.fpmt.tw
.fpmt-osel.org
.freakshare.com
.free.fr/adsl
.freechal.com
.freecn.top
.freedomchina.info
.freedomcollection.org/interviews/rebiya_kadeer
.freedomhouse.org
.freedomsherald.org
.freeforums.org
.freefq.com
.freefuckvids.com
.freegao.com
.free-hada-now.org
.freelotto.com
.freeopenvpn.com
.freeoz.org
.freeoz.org/bbs
.free-ssh.com
.freetibet.net
.freetibetanheroes.org
.freeviewmovies.com
.freevpn.me
.freewebs.com
.freexinwen.com
.freeyoutubeproxy.net
.friendsoftibet.org
.fring.com
.fromchinatousa.net
.frontlinedefenders.org
.fsurf.com
.ftchinese.com/channel/video
.ftchinese.com/comments
.ftchinese.com/story/001026807
.ftchinese.com/story/00102753
.ftchinese.com/story/001032692
.ftchinese.com/story/001037090
.ftchinese.com/story/001037091
.ftchinese.com/story/001038220
.ftchinese.com/story/001040890
.ftchinese.com/story/001042100
.ftchinese.com/story/001042252
.ftchinese.com/story/001042272
.ftchinese.com/story/001044776
.ftchinese.com/story/001045755
.ftchinese.com/story/001046118
.ftchinese.com/story/001047345
.ftchinese.com/story/001047375
.ftchinese.com/story/001047545
.ftchinese.com/story/001048710
.ftchinese.com/story/001049360
.ftchinese.com/story/001052965
.ftchinese.com/story/001053526
.ftchinese.com/story/001054103
.ftchinese.com/story/001054168
.ftchinese.com/story/001054526
.ftchinese.com/story/001054644
.ftchinese.com/story/001055299
.ftchinese.com/story/001055551
.ftchinese.com/story/001056529
.ftchinese.com/story/001056554
.ftchinese.com/story/001056567
.ftchinese.com/story/001056588
.ftchinese.com/story/001057509
.ftchinese.com/story/001057533
.ftchinese.com/story/001058295
.ftchinese.com/story/001058344
.ftchinese.com/story/001058458
.ftchinese.com/story/001058468
.ftchinese.com/story/001058561
.ftchinese.com/story/001058566
.ftchinese.com/story/001058567
.ftchinese.com/story/001058585
.ftchinese.com/story/001058628
.ftchinese.com/story/001058678
.ftchinese.com/story/001059484
.ftchinese.com/story/001059538
.ftchinese.com/story/001059818
.ftchinese.com/story/001059914
.ftchinese.com/story/001059920
.ftchinese.com/story/001060181
.ftchinese.com/story/001060493
.ftchinese.com/story/001060495
.ftchinese.com/story/001060921
.ftchinese.com/story/001061120
.ftchinese.com/story/001062028
.ftchinese.com/story/001062176
.ftchinese.com/story/001062482
.ftchinese.com/story/001062508
.ftchinese.com/story/001062741
.ftchinese.com/story/001062794
.ftchinese.com/story/001063160
.ftchinese.com/story/001063692
.ftchinese.com/story/001065287
.ftchinese.com/story/001066465
.ftchinese.com/story/001066959
.ftchinese.com/story/001067435
.ftchinese.com/story/001067545
.ftchinese.com/story/001067648
.ftchinese.com/story/001067650
.ftchinese.com/story/001068248
.ftchinese.com/story/001068278
.ftchinese.com/story/001068379
.ftchinese.com/story/001068483
.ftchinese.com/video/1437
.fuckcnnic.net
.funf.tw
.fuq.com
.furhhdl.org
.futurechinaforum.org
.fux.com
.fuyin.net
.fuyindiantai.org
.fuyu.org.tw
.g6hentai.com
.gaeproxy.com
.gaforum.org
.galaxymacau.com
.galstars.net
.gamer.com.tw
.gamez.com.tw
.gamousa.com
.gaoming.net
.gaopi.net
.gaozhisheng.net
.gaozhisheng.org
.gaybubble.com
.gaycn.net
.gaytube.com
.gazotube.com
.gcpnews.com
.gdbt.net/forum
.gelbooru.com
.geocities.co.jp
.geocities.com/SiliconValley/Circuit/5683/download.html
.gerefoundation.org
.getchu.com
.getcloak.com
.getfreedur.com
.getjetso.com/forum
.getlantern.org
.getsocialscope.com
.gfgold.com.hk
.gfsale.com
.gfw.press
.ggssl.com
.ghostpath.com
.gizlen.net
.gjczz.com
.globaltm.org
.globalvoicesonline.org
.glock.com
.gmll.org
.godsdirectcontact.org
.godsimmediatecontact.com
.gokbayrak.com
.goldbet.com
.goldenfrog.com
.goldstep.net
.gongwt.com
.goodreaders.com
.goodreads.com
.goodtv.com.tw
.goodtv.tv
.gopetition.com
.goproxing.net
.gotgeeks.com
.gotrusted.com
.gov.tw
.graphis.ne.jp
.greatfirewallofchina.org
.greenparty.org.tw
.greenpeace.com.tw
.greenreadings.com/forum
.greenvpn.net
.greenvpn.org
.guardster.com
.gu-chu-sum.org
.gun-world.net
.gyalwarinpoche.com
.gyatsostudio.com
.gzm.tv
.hacg.club
.hacg.in
.hacg.li
.hacg.red
.hacken.cc/bbs
.hanunyi.com
.harunyahya.com
.hdzog.com
.hec.su
.hecaitou.net
.hechaji.com
.hegre-art.com
.hellouk.org/forum/lofiversion
.helpeachpeople.com
.helpzhuling.org
.hentai.to
.hentaivideoworld.com
.heyzo.com
.hgseav.com
.hhdcb3office.org
.hideipvpn.com
.hideman.net
.hidemyass.com
.higfw.com
.hihiforum.com
.hilive.tv
.himalayan-foundation.org
.himemix.com
.himemix.net
.hjclub.info
.hk01.com
.hk32168.com
.hkatvnews.com
.hkbf.org
.hkbookcity.com
.hkchurch.org
.hkcmi.edu
.hkdailynews.com.hk/china.php
.hkej.com
.hkepc.com/forum/viewthread.php?tid=1153322
.hkgreenradio.org/home
.hkheadline.com*blog
.hkheadline.com/instantnews
.hkjp.org
.hklft.com
.hklts.org.hk
.hk-pub.com/forum
.hkreporter.com
.hkusu.net
.hkvwet.com
.hkwcc.org.hk
.h-moe.com
.hnntube.com
.homeperversion.com
.hongkongfp.com
.hopto.org
.hornygamer.com
.hotav.tv
.hotpornshow.com
.hotshame.com
.hotvpn.com
.hqcdp.org
.hrcchina.org
.hrcir.com
.hrea.org
.hrichina.org
.hrw.org
.hstern.net
.hstt.net
.htkou.net
.huanghuagang.org
.huangyiyu.com
.huaren.us
.hua-yue.net
.huffingtonpost.com/rebiya-kadeer
.hulkshare.com
.hurriyet.com.tr
.hut2.ru
.iav19.com
.iblist.com
.ibvpn.com
.i-cable.com
.icij.org
.icoco.com
.identi.ca
.idouga.com
.idreamx.com
.idv.tw
.ied2k.net
.ienergy1.com
.ifanr.com/857
.ifcss.org
.ift.tt
.igfw.net
.igmg.de
.igotmail.com.tw
.ihao.org/dz5
.imagefap.com
.imb.org
.imdb.com/title/tt0819354
.imdb.com/title/tt1540068
.imdb.com/title/tt4908644
.img.ly
.imkev.com
.imlive.com
.immoral.jp
.incapdns.net
.incloak.com
.indiemerch.com
.initiativesforchina.org
.inkui.com
.inmediahk.net
.inote.tw
.insecam.org
.instagram.com
.institut-tibetain.org
.i-part.com.tw
.ipjetable.net
.ipobar.com/read.php?
.iportal.me
.ipredator.se
.iptv.com.tw
.is.gd
.isaacmao.com
.islam.org.hk
.islamawareness.net/Asia/China
.islamhouse.com
.islamicity.com
.islamicpluralism.org
.islamtoday.net
.ismalltits.com
.istars.co.nz
.istiqlalhewer.com
.istockphoto.com
.italiatibet.org
.its.caltech.edu/~falun/
.itsky.it
.itweet.net
.iu45.com
.iuksky.com
.ivacy.com
.iverycd.com
.ivpn.net
.ixxx.com
.izaobao.us
.izles.net
.izlesem.org
.jamyangnorbu.com
.jav68.tv
.javakiba.org
.javbus.com
.javhip.com
.javlibrary.com
.javmoo.com
.javmoo.xyz
.javseen.com
.javtag.com
.javzoo.com
.jdwsy.com
.jiangweiping.com
.jiehua.cz
.jingsim.org
.jizzthis.com
.jkb.cc
.journalchretien.net
.juhuaren.com
.june4commemoration.org
.junefourth-20.net
.justicefortenzin.org
.jyxf.net
.kagyuoffice.org
.kaiyuan.de
.kakao.com
.kankan.today
.kannewyork.com
.kanshifang.com
.kaotic.com
.karmapa.org
.karmapa-teachings.org
.kat.cr
.kba-tx.org
.kcoolonline.com
.kebrum.com
.kechara.com
.keepandshare.com/visit/visit_page.php?i=688154
.kendincos.net
.kenengba.com
.kepard.com
.khabdha.org
.khmusic.com.tw
.kindleren.com
.kingdomsalvation.org
.kink.com
.kir.jp
.kissbbao.cn
.knowledgerush.com/kr/encyclopedia
.konachan.com
.koornk.com
.ksnews.com.tw
.kui.name/event
.kurashsultan.com
.kzeng.info
.lalulalu.com
.lamayeshe.com
.lamnia.co.uk
.lanterncn.cn
.lantosfoundation.org
.laod.cn
.laoyang.info
.laqingdan.net
.lastcombat.com
.latibet.org
.leafyvpn.net
.legalporno.com
.lemonde.fr
.lhakar.org
.lhasocialwork.org
.liangyou.net
.lianyue.net
.liaowangxizang.net
.libertytimes.com.tw
.lidecheng.com/blog/fucking-gfw
.lighten.org.tw
.linglingfa.com
.linkideo.com
.lionsroar.com
.lipuman.com
.liuhanyu.com
.liujianshu.com
.livedoor.jp
.liveleak.com
.livestation.com
.livevideo.com
.liwangyang.com
.load.to
.lobsangwangyal.com
.localdomain.ws
.londonchinese.ca
.longhair.hk
.looktoronto.com
.lotsawahouse.org/tibetan-masters/fourteenth-dalai-lama
.lotuslight.org.hk
.lotuslight.org.tw
.lrip.org
.lsd.org.hk
.lsm.org
.lsmchinese.org
.lsmkorean.org
.lsmradio.com/rad_archives
.lsmwebcast.com
.lsxszzg.com
.ltn.com.tw
.luke54.com
.luke54.org
.lupm.org
.lyfhk.net
.macrovpn.com
.maiio.net
.maiplus.com
.makzhou.warehouse333.com
.malaysiakini.com
.maniash.com
.mansion.com
.mansionpoker.com
.maplew.com
.martsangkagyuofficial.org
.marxist.com
.marxists.org/chinese
.maxing.jp
.mcaf.ee
.md-t.org
.mediachinese.com
.mediafire.com/?
.mediafire.com/download
.mediafreakcity.com
.medium.com
.megaporn.com
.meltoday.com
.memehk.com
.memri.org
.memrijttm.org
.mercyprophet.org
.meridian-trust.org
.meripet.biz
.meripet.com
.mesotw.com/bbs
.metrohk.com.hk/?cmd=detail&categoryID=2
.metroradio.com.hk
.meyul.com
.mihk.hk/forum
.mihr.com
.milph.net
.milsurps.com
.mimivip.com
.mimivv.com
.mindrolling.org
.minghui.or.kr
.mingjinglishi.com
.mingpao.com
.mingpaocanada.com
.mingpaomonthly.com
.mingpaony.com
.mingpaosf.com
.mingpaotor.com
.mingpaovan.com
.mingshengbao.com
.minhhue.net
.miniforum.org
.ministrybooks.org
.minzhuhua.net
.mixero.com
.mixx.com
.mk5000.com
.mlcool.com
.mmmca.com
.mobile01.com
.mobypicture.com
.mofos.com
.moonbbs.com
.motherless.com
.mousebreaker.com
.movements.org
.mp3buscador.com
.mswe1.org
.m-team.cc
.mullvad.net
.mummysgold.com
.murmur.tw
.musicade.net
.muslimvideo.com
.myaudiocast.com
.myav.com.tw/bbs
.mybbs.us
.myca168.com
.mychinamyhome.com
.mychinanet.com
.mychinanews.com
.myeasytv.com
.my-formosa.com
.myforum.com.hk
.myfreepaysite.com
.myfreshnet.com
.my-private-network.co.uk
.my-proxy.com
.myspace.com
.mytalkbox.com
.nakido.com
.nakuz.com/bbs
.namgyal.org
.nanyang.com
.nanyangpost.com
.nanzao.com
.naol.ca
.nationsonline.org/oneworld/tibet
.nbtvpn.com
.nch.com.tw
.ncn.org
.nde.de
.ndr.de
.ned.org
.netbirds.com
.network54.com
.new96.ca
.new-akiba.com
.newcenturymc.com
.newchen.com
.newgrounds.com
.newlandmagazine.com.au
.newnews.ca
.news.now.com
.newsancai.com
.newscn.org
.newsdh.com
.newtaiwan.com.tw
.next11.co.jp
.nextmag.com.tw
.nextmedia.com
.nhentai.net
.nicovideo.jp/watch
.ninjacloak.com
.no-ip.org
.norbulingka.org
.nowtorrents.com
.noypf.com
.npnt.me
.nps.gov
.nrk.no
.ntd.tv
.ntdtv.co.kr
.ntrfun.com
.nubiles.net
.nukistream.com
.nuvid.com
.nvquan.org
.nwtca.org
.nydus.ca
.nytimes.com
.nzchinese.com
.obutu.com
.ocreampies.com
.oikos.com.tw/v4
.oiktv.com
.okayfreedom.com
.olympicwatch.org
.onlinecha.com
.onthehunt.com
.oopsforum.com
.openervpn.in
.openleaks.org
.organcare.org.tw
.orgfree.com
.otnd.org
.oursweb.net
.ozchinese.com/bbs
.ozxw.com
.ozyoyo.com
.pacificpoker.com
.packetix.net
.padmanet.com
.palacemoon.com
.paldengyal.com
.paltalk.com
.pandapow.net
.pandavpn-jp.com
.pandora.tv
.panluan.net
.paradisepoker.com
.partycasino.com
.partypoker.com
.passion.com
.passiontimes.hk
.pastie.org
.pchome.com.tw
.pcstore.com.tw/ntdtvapshop
.peeasian.com
.pekingduck.org
.pemulihan.or.id
.penchinese.net
.penthouse.com
.pentoy.hk/%E4%B8%AD%E5%9C%8B
.pentoy.hk/%E6%99%82%E4%BA%8B
.peoplebookcafe.com
.peoplenews.tw
.peopo.org
.percy.in
.perfectgirls.net
.persecutionblog.com
.picidae.net
.pin6.com
.ping.fm
.piposay.com
.piring.com
.pixnet.net
.pk.com
.playboyplus.com
.playno1.com
.plus28.com
.plusbb.com
.pmates.com
.pokerstars.net
.polymerhk.com
.popo.tw
.porn.com
.porn2.com
.porn5.com
.pornbase.org
.pornerbros.com
.pornhost.com
.pornhub.com
.pornoxo.com
.pornrapidshare.com
.pornsharing.com
.pornstarclub.com
.porntube.com
.porntubenews.com
.porntvblog.com
.pornvisit.com
.portablevpn.nl
.post852.com
.postimg.org
.power.com
.powerphoto.org
.prisoneralert.com
.pritunl.com
.private.com/home
.proxfree.com
.proxpn.com
.proxylist.org.uk
.proxynetwork.org.uk
.proxypy.net
.proxytunnel.net
.psiphon3.com
.ptt.cc
.pttvan.org
.puffstore.com
.punyu.com/puny
.purplelotus.org
.pussyspace.com
.putihome.org
.putlocker.com/file
.puuko.com
.python.com.tw
.qanote.com
.qgirl.com.tw
.qidian.ca
.qienkuen.org
.qkshare.com
.quitccp.net
.quitccp.org
.quran.com
.quranexplorer.com
.qvodzy.org
.ra.gg
.radicalparty.org
.radiohilight.net
.raidtalk.com.tw
.rainbowplan.org/bbs
.raizoji.or.jp
.rapbull.net
.raremovie.cc
.raremovie.net
.read100.com
.readingtimes.com.tw
.readydown.com
.realcourage.org
.realraptalk.com
.recordhistory.org
.recovery.org.tw
.redchinacn.net
.relay.com.tw
.releaseinternational.org
.renyurenquan.org
.reuters.com
.revleft.com
.rfa.org
.rfachina.com
.rfamobile.org
.rfi.fr
.rhcloud.com
.rigpa.org
.rileyguide.com
.ritouki.jp
.rlwlw.com
.rmjdw.com
.rmjdw132.info
.roadshow.hk
.roodo.com
.rosechina.net
.rotten.com
.rsf.org
.rsf-chinese.org
.rsgamen.org
.rssmeme.com
.rthk.hk
.rthk.org.hk
.rtycminnesota.org
.ruanyifeng.com/blog*some_ways_to_break_the_great_firewall
.rushbee.com
.ruyiseek.com
.rxhj.net
.s1s1s1.com
.safervpn.com
.saiq.me
.sakya.org
.salvation.org.hk
.samair.ru/proxy/type-01
.sambhota.org
.sanmin.com.tw
.savetibet.org
.sbme.me
.scasino.com
.sciencenets.com
.scieron.com
.scmp.com
.scmpchinese.com
.scribd.com
.s-dragon.org
.searchtruth.com
.secretsline.biz
.sendspace.com
.sesawe.org
.sevenload.com
.sex.com
.sex-11.com
.sexandsubmission.com
.sexbot.com
.sexhu.com
.sexhuang.com
.sextvx.com
.sfileydy.com
.sftindia.org
.sftuk.org
.shadowsky.xyz
.shadowsocks.org
.shambhalasun.com
.shangfang.org
.sharebee.com
.sharpdaily.hk
.sharpdaily.tw
.shat-tibet.com
.shellfire.de
.shenshou.org
.shiatv.net
.shicheng.org
.shitaotv.org
.shop2000.com.tw
.shopping.com
.showhaotu.com
.showtime.jp
.shwchurch.org
.shwchurch3.com
.sidelinessportseatery.com
.sijihuisuo.com
.sinchew.com.my/node/
.sinchew.com.my/taxonomy/term
.singaporepools.com.sg
.singfortibet.com
.sinoants.com
.sinonet.ca
.sinopitt.info
.sinoquebec.com
.sitebro.tw
.sjrt.org
.slaytizle.com
.slideshare.net
.slinkset.com
.slutload.com
.slyip.com
.slyip.net
.smh.com.au/world/death-of-chinese-playboy-leaves-fresh-scratches-in-party-paintwork-20120903-25a8v
.smith.edu/dalailama
.smyxy.org
.snaptu.com
.sobees.com
.socrec.org
.sod.co.jp
.softether.co.jp
.softether.org
.softether-download.com
.so-ga.net
.so-news.com
.songjianjun.com
.sonicbbs.cc
.sonidodelaesperanza.org
.sopcast.com
.sopcast.org
.sorazone.net
.sostibet.org
.soubory.com
.soulcaliburhentai.net
.soul-plus.net
.soumo.info
.soundofhope.kr
.sourcewadio.com
.spankwire.com
.spike.com
.spotflux.com
.spring4u.info
.srcf.ucam.org/salon/
.sspro.ml
.stage64.hk
.starp2p.com
.startpage.com
.state168.com
.stepchina.com
.stickam.com
.stileproject.com
.sto.cc
.stoptibetcrisis.net
.storm.mg
.stormmediagroup.com
.strongwindpress.com
.student.tw/db
.sugarsync.com
.sugobbs.com
.sumrando.com
.sunporno.com
.sunskyforum.com
.sunvpn.net
.suoluo.org
.supervpn.net
.suprememastertv.com
.surfeasy.com
.surfeasy.com.au
.suroot.com
.suyangg.com
.swissvpn.net
.sydneytoday.com
.sylfoundation.org
.sytes.net
.szbbs.net
.t.co
.t35.com
.t66y.com
.taa-usa.org
.taaze.tw
.tacem.org
.taconet.com.tw
.tafm.org
.tagwa.org.au
.taipeisociety.org
.taiwanbible.com
.taiwancon.com
.taiwandaily.net
.taiwandc.org
.taiwanjustice.com
.talk853.com
.talkboxapp.com
.talkonly.net
.tangren.us
.taoism.net
.taolun.info
.tascn.com.au
.taweet.com
.tbcollege.org
.tbi.org.hk
.tbicn.org
.tbjyt.org
.tbsmalaysia.org
.tbsn.org
.tbsseattle.org
.tbssqh.org
.tbtemple.org.uk
.tbthouston.org
.tccwonline.org
.tcewf.org
.teeniefuck.net
.telecomspace.com
.telegramdownload.com
.tenacy.com
.tew.org
.thaicn.com
.thebobs.com
.thechinabeat.org
.thedalailamamovie.com
.thegly.com
.thehots.info
.theinitium.com
.thenewslens.com
.thetibetmuseum.org
.thetibetpost.com
.thinkingtaiwan.com
.thisav.com
.thlib.org
.thumbzilla.com
.thywords.com.tw
.tiananmenduizhi.com
.tianhuayuan.com
.tianlawoffice.com
.tianzhu.org
.tibet.a.se
.tibet.at
.tibet.com
.tibet.net
.tibet.org
.tibet.to
.tibet3rdpole.org
.tibetaid.org
.tibetan.fr
.tibetanaidproject.org
.tibetanarts.org
.tibetanbuddhistinstitute.org
.tibetancommunityuk.net
.tibetanlanguage.org
.tibetanliberation.org
.tibetanpaintings.com
.tibetanphotoproject.com
.tibetanpoliticalreview.org
.tibetanreview.net
.tibetanwomen.org
.tibetanyouth.org
.tibetanyouthcongress.org
.tibetcharity.dk
.tibetchild.org
.tibetcity.com
.tibetcollection.com
.tibetcorps.org
.tibet-envoy.eu
.tibetexpress.net
.tibet-foundation.org
.tibetgermany.com
.tibethaus.com
.tibetheritagefund.org
.tibet-house-trust.co.uk
.tibetinfonet.net
.tibetjustice.org
.tibetkomite.dk
.tibet-munich.de
.tibetoffice.ch
.tibetoffice.com.au
.tibetonline.tv
.tibetoralhistory.org
.tibetpolicy.eu
.tibetrelieffund.co.uk
.tibetsociety.com
.tibetsun.com
.tibetsupportgroup.org
.tibetswiss.ch
.tibettelegraph.com
.ticket.com.tw
.timdir.com
.time.com
.timsah.com
.tiny.cc
.tistory.com
.tmagazine.com
.tmdfish.com
.tmpp.org
.tnaflix.com
.tngrnow.com
.tngrnow.net
.tnp.org
.tokyo-247.com
.tokyo-hot.com
.tongil.or.kr
.tono-oka.jp
.toodoc.com
.topnews.in
.to-porno.com
.topshareware.com
.topsy.com
.torcn.com
.torguard.net
.torproject.org
.tparents.org
.tpi.org.tw
.trialofccp.org
.trimondi.de/SDLE
.trouw.nl
.trt.net.tr
.truebuddha-md.org
.truth101.co.tv
.truthontour.org
.truveo.com
.tsctv.net
.tsctv.net
.tsemtulku.com
.tsu.org.tw
.tttan.com
.tuanzt.com
.tubaholic.com
.tube.com
.tube911.com
.tubecup.com
.tubegals.com
.tubeislam.com
.tuidang.se
.tumblr.com
.tumutanzi.com
.tunein.com
.tuo8.cc
.tuo8.club
.tuo8.hk
.tuo8.in
.tuo8.ninja
.tuo8.org
.tuo8.pw
.turansam.org
.turbobit.net
.turbohide.com
.tushycash.com
.tuvpn.com
.tv.com
.tvboxnow.com
.tvmost.com.hk
.tvplayvideos.com
.tw01.org
.twaitter.com
.twaud.io
.twbbs.net.tw
.tweepml.org
.tweetbackup.com
.tweetboner.biz
.tweetdeck.com
.tweettunnel.com
.twibble.de
.twiends.com
.twifan.com
.twilightsex.com
.twit2d.com
.twitlonger.com
.twitpic.com
.twitstat.com
.twitter.com
.twittercounter.com
.twittergadget.com
.twitterkr.com
.twitturly.com
.twitvid.com
.twitzap.com
.twnorth.org.tw
.tw-npo.org
.twtkr.com
.twyac.org
.txxx.com
.tycool.com
.ubddns.org
.uc-japan.org
.udn.com
.ugo.com
.uighur.nl
.ulike.net
.unblockdmm.com
.uncyclopedia.hk/wiki
.uni.cc
.unification.net
.unification.org.tw
.unitedsocialpress.com
.unix100.com
.unodedos.com
.untraceable.us
.upholdjustice.org
.upload4u.info
.uploadstation.com/file
.upornia.com
.upwill.org
.usaip.eu
.ustream.tv
.utopianpal.com
.uu-gg.com
.uvwxyz.xyz
.uwants.com
.uwants.net
.uyghurcanadiansociety.org
.uyghurensemble.co.uk
.uyghurpen.org
.uyghurpress.com
.uyghurstudies.org
.v2ex.com
.v2ray.com
.van001.com
.van698.com
.vanemu.cn
.vanilla-jp.com
.vanpeople.com
.vegasred.com
.velkaepocha.sk
.venbbs.com
.venchina.com
.versavpn.com
.vft.com.tw
.viber.com
.vica.info
.victimsofcommunism.org
.videodetective.com
.videomega.tv
.videomo.com
.vidinfo.org/video
.vijayatemple.org
.vital247.org
.vivahentai4u.net
.vivatube.com
.vivthomas.com
.vjmedia.com.hk
.vllcs.org
.voacantonese.com
.voachineseblog.com
.voanews.com
.voatibetanenglish.com
.vocativ.com
.vot.org
.vovo2000.com
.voxer.com
.voy.com
.vpn4all.com
.vpnaccount.org
.vpncoupons.com
.vpnfan.com
.vpnforgame.net
.vpngate.net
.vpngratis.net
.vpninja.net
.vpnmaster.com
.vpnpick.com
.vpnreactor.com
.vpnsecure.me
.vpnsp.com
.vpntunnel.com
.vpnuk.info
.vpnvip.com
.vporn.com
.wahas.com
.waigaobu.com
.waiwaier.com
.wallproxy.com
.wangjinbo.org
.wango.org
.watchinese.com
.wattpad.com
.wdf5.com
.wearehairy.com
.wearn.com
.webevader.org
.webfreer.com
.webjb.org
.webrush.net
.websitepulse.com/help/testtools.china-test
.webwarper.net
.weekmag.info
.wefong.com
.weiming.info
.welovecock.com
.wemigrate.org
.wenhui.ch
.wenyunchao.com
.westca.com
.westernshugdensociety.org
.westkit.net
.wetplace.com
.wforum.com
.whatblocked.com
.whippedass.com
.wikileaks.org
.wikileaks-forum.com
.wisdompubs.org
.wisevid.com
.witnessleeteaching.com
.witopia.net
.wjbk.org
.wnacg.com
.wo.tc
.wokar.org
.wordpress.com
.workerdemo.org.hk
.worldcat.org
.worldvpn.net
.wow.com
.wow-life.net
.woyaolian.org
.wpoforum.com
.wqyd.org
.wsj.com
.wsj.net
.wsjhk.com
.wtbn.org
.wtfpeople.com
.wwitv.com
.x-berry.com
.xbookcn.com
.xcritic.com
.xfm.pp.ru
.xianchawang.net
.xianjian.tw
.xianqiao.net
.xiaochuncnjp.com
.xiaohexie.com
.xihua.es
.xing.com
.xinmiao.com.hk
.xiongpian.com
.xiuren.org
.xrentdvd.com
.xskywalker.com
.xvideos.com
.xxbbx.com
.xxlmovies.com
.xxxymovies.com
.yanghengjun.com
.yasni.co.uk
.ydy.com
.yeahteentube.com
.yes-news.com
.yibada.com
.yibaochina.com
.yidio.com
.yingsuoss.com
.yipub.com
.yobt.com
.yogichen.org
.yorkbbs.ca
.youjizz.com
.youpai.org
.youporn.com
.youporngay.com
.your-freedom.net
.yourlisten.com
.yourlust.com
.yourprivatevpn.com
.yousendit.com
.youthnetradio.org/tmit/forum
.youtube.com
.youtubecn.com
.yuanzhengtang.org
.yulghun.com
.yuvutu.com
.ywpw.com/forums/history/post/A0/p0/html/227
.yyii.org
.yzzk.com
.zalmos.com
.zaobao.com
.zaobao.com.sg
.zaozon.com
.zello.com
.zengjinyan.org
.zfreet.com
.zgsddh.com
.zhanbin.net
.zhangboli.net
.zhenlibu1984.com
.zhinengluyou.com
.zhuanxing.cn
.ziddu.com/download
.ziporn.com
.zkaip.com
.zonaeuropa.com
.zonghexinwen.net
.zoozle.net
.zshare.net/download
.zsrhao.com
.zuo.la
.zuola.com
.zzcartoon.com
0to255.com
1000giri.net
10musume.com
12bet.com
12vpn.com
12vpn.net
173ng.com
1984bbs.com
1984bbs.org
1-apple.com.tw
1e100.net
1pondo.tv
2008xianzhang.info
2017.hk
24hrs.ca
32red.com
36rain.com
4bluestones.biz
4everproxy.com
4rbtv.com
4shared.com
4tern.com
51.ca
51luoben.com
63i.com
6park.com
7capture.com
881903.com
89-64.org
8z1.net
91porn.com
99btgc01.com
9bis.com
9bis.net
a248.e.akamai.net
abc.pp.ru
abc.xyz
aboluowang.com
acevpn.com
acgkj.com
activpn.com
aculo.us
addictedtocoffee.de
admob.com
adorama.com
adult-sex-games.com
advanscene.com
advertfan.com
aenhancers.com
af.mil
agnesb.fr
agoogleaday.com
ai-kan.net
aiph.net
airconsole.com
airvpn.org
ait.org.tw
aiweiweiblog.com
akiba-online.com
akiba-web.com
alabout.com
alasbarricadas.org
alforattv.net
alien-ufos.com
alkasir.com
allconnected.co
alldrawnsex.com
allmovie.com
allonlinux.free.fr
al-qimmah.net
alternate-tools.com
altrec.com
alwaysdata.com
alwaysdata.net
alwaysvpn.com
am730.com.hk
ameblo.jp
americangreencard.com
amiblockedornot.com
amnesty.org
amnestyusa.org
ampproject.org
anchorfree.com
ancsconf.org
andfaraway.net
android.com
androidify.com
android-x86.org
angularjs.org
aniscartujo.com
anobii.com
anonymitynetwork.com
a-normal-day.com
anthonycalzadilla.com
aobo.com.au
aolchannels.aol.com
aomiwang.com
api.linksalpha.com
apiary.io
apidocs.linksalpha.com
apigee.com
apkpure.com
app.box.com
appsocks.net
appspot.com
appsto.re
archive.org
archives.gov
areca-backup.org
arena.taipei
arethusa.su
arlingtoncemetery.mil
army.mil
arstechnica.com
asacp.org
asahichinese.com
asiaharvest.org
asiansexdiary.com
asianspiss.com
asianwomensfilm.de
askstudent.com
askynz.net
assembla.com
astonmartinnews.com
astrill.com
atc.org.au
atdmt.com
athenaeizou.com
atj.org.tw
atlaspost.com
atnext.com
avaaz.org
avdb.in
avdb.tv
avidemux.org
avmoo.pw
avoision.com
axureformac.com
azubu.tv
backchina.com
baidu.jp
bailandaily.com
baixing.me
banana-vpn.com
bangyoulater.com
bannedbook.org
barnabu.co.uk
barracuda.com
bayvoice.net
bbcchinese.com
bbchat.tv
bb-chat.tv
bbs.mychat.to
bbsfeed.com
bebo.com
beeg.com
beevpn.com
beijing1989.com
beijingspring.com
berlintwitterwall.com
bestforchina.org
bestvpn.com
bet365.com
bettervpn.com
bettween.com
betvictor.com
bfnn.org
bfsh.hk
bgvpn.com
bigjapanesesex.com
bignews.org
billywr.com
bitcointalk.org
bitshare.com
bjzc.org
blackvpn.com
bl-doujinsouko.com
blinkx.com
blip.tv/
blockcn.com
blog.de
blog.exblog.co.jp
blog.expofutures.com
blog.fizzik.com
blog.kangye.org
blog.pathtosharepoint.com
blog.pentalogic.net
blog.tiney.com
blogblog.com
blogcatalog.com
blogcity.me
blogger.com
bloglines.com
bloglovin.com
blogs.tampabay.com
bloodshed.net
bloomberg.cn
bloomberg.com
bloomberg.de
bloombergview.com
bloomfortune.com
bnrmetal.com
boardreader.com
bolehvpn.net
boobstagram.com
book.com.tw
books.com.tw
botanwang.com
bowenpress.com
boxpn.com
boxun*.azurewebsites.net
boxun.com
boxun.tv
boxunblog.com
boysmaster.com
br.st
brandonhutchinson.com
braumeister.org
bravotube.net
brazzers.com
break.com
breakingtweets.com
breakwall.net
brizzly.com
broadpressinc.com
brutaltgp.com
bt95.com
btku.me
btku.org
budaedu.org
bullog.org
bullogger.com
bx.tl
cablegatesearch.net
cactusvpn.com
calebelston.com
camfrog.com
cams.com
caobian.info
caochangqing.com
cap.org.hk
carfax.com
caribbeancom.com
casino.williamhill.com
casinobellini.com
catch22.net
catfightpayperview.xxx
catholic.org.hk
catholic.org.tw
cattt.com
cbc.ca
cbs.ntu.edu.tw
ccdtr.org
cchere.com
ccthere.com
cdbook.org
cdd.me
cdef.org
cdig.info
cdjp.org
cdn.helixstudios.net
cdn.printfriendly.com
cdn.softlayer.net
cdninstagram.com
cdp1998.org
cdp2006.org
cdpweb.org
cdpwu.org
cdw.com
cecc.gov
cellulo.info
cenews.eu
centauro.com.br
centerforhumanreprod.com
centralnation.com
certificate-transparency.org
c-est-simple.com
change.org
changp.com
chenguangcheng.com
chenshan20042005.wordpress.com
cherrysave.com
china101.com
china18.org
china21.com
china21.org
chinaaffairs.org
chinaaid.me
chinachannel.hk
chinacomments.org
chinadigitaltimes.net
chinaelections.org
chinaeweekly.com
chinafreepress.org
chinagfw.org
chinagreenparty.org
chinahorizon.org
chinainperspective.net
chinainperspective.org
chinainterimgov.org
china-mmm.net
chinamule.com
chinapress.com.my
chinasocialdemocraticparty.com
chinasoul.org
chinatopsex.com
chinaworker.info
chinayuanmin.org
chinesedailynews.com
chinesedemocracy.com
chinesegay.org
chinesen.de
chingcheong.com
christianstudy.com
christiantimes.org.hk
chrome.com
chromeadblock.com
chromecast.com
chromeexperiments.com
chromercise.com
chromestatus.com
chromium.org
circlethebayfortibet.org
citizenscommission.hk
civicparty.hk
civilhrfront.org
civilmedia.tw
ck101.com
cl.ly
classicalguitarblog.net
cldr.unicode.org
clementine-player.org
club1069.com
cms.gov
cmule.com
cmule.org
cna.com.tw
cnd.org
cnpolitics.org
co.ng.mil
coat.co.jp
cochina.co
cochina.org
codeshare.io
codeskulptor.org
collateralmurder.com
collateralmurder.org

comefromchina.com
commentshk.com
communistcrimes.org
communitychoicecu.com
compileheart.com
connect.facebook.net
contests.twilio.com
coolaler.com
coolder.com
coolloud.org.tw
cotweet.com
couchdbwiki.com
cpj.org/
crackle.com
crchina.org
creaders.net
cristyli.com
crossfire.co.kr
crossthewall.net
csdparty.com
c-spanvideo.org
css.pixnet.in
csuchen.de
cuihua.org
cuiweiping.net
culture.tw
cumlouder.com
curvefish.com
cusu.hk
cyberghostvpn.com
cynscribe.com
d3rhr7kgmtrq1v.cloudfront.net
dabr.co.uk
dabr.me
dabr.mobi
dadazim.com
dailidaili.com
dailymotion.com
dajiyuan.de
dalailama.ru
dalailamaworld.com
dalianmeng.org
daliulian.org
danke4china.net
darpa.mil
dastrassi.org
data-vocabulary.org
daxa.cn
db.tt
dcard.tw
decodet.co
deepmind.com
default.secureserver.net
deja.com
delcamp.net
demo.opera-mini.net
democrats.org
derekhsu.homeip.net
desc.se
de-sci.org
desipro.de
dessci.com
deutsche-welle.de
developers.box.net
devio.us
devpn.com
dfas.mil
diaoyuislands.org
digisfera.com
digitalnomadsproject.org
diigo.com
dilber.se
dimitrik.free.fr
directcreative.com
discuss.com.hk
dish.com
disqus.com
dit-inc.us
dizhuzhishang.com
djorz.com
dl.box.net
dl-laby.jp
dlsite.com
dm530.net
dmcdn.net
dmm.co.jp
dns2go.com
dnscrypt.org
dnssec.net
dolc.de
dolf.org.hk
dollf.com
dongtaiwang.com
dongtaiwang.net
dontmovetochina.com
dotplane.com
dotsub.com
dougscripts.com
doujincafe.com
dpp.org.tw
dpr.info
dragonsprings.org
draw.io
dreammask.org
drgan.net
dropbox.com
dropboxusercontent.com
dtiblog.com
dtic.mil
duckduckgo.com
duckmylife.com
duihua.org
duihuahrjournal.org
duoweitimes.com
duplicati.com
dvorak.org
dw.de
dwnews.com
dwnews.net
dw-world.com
dynawebinc.com
eastturkistangovernmentinexile.us
ebook.hyread.com.tw
ecfa.org.tw
e-classical.com.tw
edgecastcdn.net
edubridge.com
eesti.ee
eevpn.com
efksoft.com
e-gold.com
eic-av.com
eksisozluk.com
elephantvpn.com
elgoog.im
elpais.com
embr.in
enewstree.com
englishfromengland.co.uk
entermap.com
epochtimes.co.il
epochtimes.co.kr
epochtimes.com
epochtimes-bg.com
epochtimes-romania.com
epochweek.com
epochweekly.com
erights.net
eriversoft.com
ernestmandel.org
erodaizensyu.com
erodoujinworld.com
eromangadouzin.com
eromanga-kingdom.com
etizer.org
etokki.com
etools.ncol.com
eu.org
exblog.jp
exchristian.hk
exmormon.org
expatshield.com
expekt.com
exploader.net
extmatrix.com
eyevio.jp
eyny.com
facebook.br
facebook.com
facebook.hu
facebook.in
facebook.nl
facebook.se
facebookquotes4u.com
faceless.me
facesofnyfw.com
faiththedog.info
fakku.net
falsefire.com
falundafa-florida.org
falundafaindia.org
falundafa-nc.org
falundafa-pa.net
falunhr.org
falunworld.net
famunion.com
fangbinxing.com
fanglizhi.info
fangmincn.org
fangong.org
fanqianghou.com
fanswong.com
fast.wistia.com
fastpic.ru
fastssh.com
faststone.org
favstar.fm
fb.com
fb.me
fbcdn.net
fbsbx.com
fc2cn.com
feedburner.com
feelssh.com
feministteacher.com
fengzhenghu.com
fengzhenghu.net
fileflyer.com
filesor.com
finalion.jp
financetwitter.com
finchvpn.com
findmima.com
fireofliberty.org
firetweet.io
firstfivefollowers.com
flecheinthepeche.fr
flgg.us
flickr.com
flipboard.com
flipkart.com
flitto.com
focustaiwan.tw
fofg.org
fooooo.com
fotop.net
fourface.nodesnoop.com
fourthinternational.org
foxdie.us
foxsub.com
fpmtmexico.org
fqrouter.com
franklc.com
free4u.com.ar
freealim.com
freebrowser.org
freedomchina.info
freedomhouse.org
freedomsherald.org
freegao.com
freelotto.com
freenetproject.org
freeoz.org
free-ssh.com
freessh.us
freetibet.org
freewallpaper4.me
freeweibo.com
freeyoutubeproxy.net
fring.com
fringenetwork.com
frommel.net
fscked.org
fuckcnnic.net
fullerconsideration.com
furbo.org
furinkan.com
furl.net
futuremessage.org
fw.cm
fxnetworks.com
g.co
g.e-hentai.org
gabocorp.com
galenwu.com
game735.com
gamer.com.tw
gamez.com.tw
gaoming.net
gardennetworks.org
gartlive.com
gather.com
gaymap.cc
gazotube.com
gcc.org.hk
gclooney.com
gcr.io
geek-art.net
geekheart.info
geekmanuals.com
geohot.com
geometrictools.com
get.how
getcloak.com
getcloudapp.com
getfoxyproxy.org
getgom.com
getlantern.org
getmdl.io
getsmartlinks.com
gettyimages.com
getuploader.com
gfsale.com
ggpht.com
ggssl.com
ghost.org
ghostpath.com
ghut.org
giga-web.jp
girlbanker.com
git.io
git-scm.com
gizlen.net
glass8.eu
glennhilton.com
globalrescue.net
globalvoicesonline.org
glype.com
gmail.com
gmhz.org
gmodules.com
gmozomg.izihost.org
gnci.org.hk
go141.com
goagent.biz
goagentplus.com
godfootsteps.org
gohappy.com.tw
golang.org
goldbetsports.com
goldenfrog.com
goldwave.com
goo.gl
goodreaders.com
goodreads.com
goofind.com
gopetition.com
gospelherald.com
gotrusted.com
gotw.ca
g-queen.com
grammaly.com
grangorz.org
graphis.ne.jp
graylog2.org
greasespot.net
greatfire.org
greatfire.us7.list-manage.com
greatfirewallofchina.net
greatfirewallofchina.org
greatroc.tw
greenfieldbookstore.com.hk
greenpeace.org
greenvpn.net
gtricks.com
guishan.org
gunsamerica.com
gutteruncensored.com
gvm.com.tw
gvt0.com
gvt1.com
gvt3.com
gzone-anime.info
hacg.club
hackthatphone.net
hakkatv.org.tw
happy-vpn.com
hardsextube.com
hasaowall.com
hautelook.com
hautelookcdn.com
h-china.org
hdtvb.net
heartyit.com
hecaitou.net
hechaji.com
heeact.edu.tw
helloandroid.com
helloqueer.com
hellotxt.com
help.linksalpha.com
helpeachpeople.com
helplinfen.com
helpster.de
heungkongdiscuss.com
hexxeh.net
hidden-advent.org
hide.me
hideipvpn.com
hideman.net
hidemyass.com
hidemycomp.com
highrockmedia.com
hihistory.net
hiitch.com
hikinggfw.org
himemix.com
hk.jiepang.com
hk.news.yahoo.com
hk32168.com
hkbookcity.com
hkcoc.com
hkfaa.com
hkip.org.uk
hklts.org.hk
hkreporter.com
hkusu.net
hkzone.org
hmvdigital.ca
hmvdigital.com
hnjhj.com
hola.com
hola.org
holyspiritspeaks.org
homedepot.com
hongkongfp.com
hongzhi.li
hootsuite.com
hoovers.com
hotspotshield.com
hotvpn.com
hougaige.com
howtoforge.com
hqcdp.org
hqjapanesesex.com
hrichina.org
hrw.org
hsjp.net
hsselite.com
htkou.net
html5rocks.com
htmldog.com
huanghuagang.org
huaren.us
huayuworld.org
hudatoriq.web.id
hugoroy.eu
huhaitai.com
huhamhire.com
hulu.com
huluim.com
hungerstrikeforaids.org
hung-ya.com
huping.net
hutianyi.net
hwayue.org.tw
hwinfo.com
hybrid-analysis.com
hyperrate.com
i1.hk
i2p2.de
i2runner.com
i818hk.com
iam.soy
iask.bz
iask.ca
iblogserv-f.net
ibvpn.com
icij.org
icl-fi.org
icoco.com
iconpaper.org
icu-project.org
identi.ca
idiomconnection.com
ifan.cz.cc
ifcss.org
ifreewares.com
igcd.net
igfw.net
ignitedetroit.net
igoogle.com
igvita.com
ihakka.net
iicns.com
illusionfactory.com
ilove80.be
ilovelongtoes.com
im.tv
im88.tw
imagefap.com
imageflea.com
images.comico.tw
imagevenue.com
imagezilla.net
img*.picturedip.com
img.ly
imkev.com
incloak.com
incredibox.fr
indiandefensenews.in
indiemerch.com
inmediahk.net
innermongolia.org
instagram.com
interfaceaddiction.com
internationalrivers.org
internetpopculture.com
inxian.com
ipcf.org.tw
iphone4hongkong.com
iphonehacks.com
iphonetaiwan.org
iphonix.fr
ipicture.ru
ipjetable.net
ippotv.com
ipredator.se
ipvanish.com
ironbigfools.compython.net
ironicsoftware.com
ironpython.net
isaacmao.com
isgreat.org
islamhouse.com
ismaelan.com
ismprofessional.net
israbox.com
itaboo.info
itasoftware.com
itshidden.com
iuhrdf.org
ivacy.com
ixquick.com
iyouport.com
j.mp
janwongphoto.com
japan-whores.com
javfor.me
javhub.net
javhuge.com
javlibrary.com
jcpenney.com
jgoodies.com
jiangweiping.com
jiaoyou8.com
jinbushe.org
jingpin.org
jitouch.com
jma.go.jp
joachims.org
jobso.tv
joeedelman.com
journalofdemocracy.org
jpl.nasa.gov
juliepost.com
juliereyc.com
junauza.com
junefourth-20.net
juziyue.com
jwmusic.org
kagyuoffice.org
kagyuoffice.org.tw
kakao.com
kanshifang.com
karayou.com
ka-wai.com
kawaiikawaii.jp
kcsoftwares.com
kebrum.com
kenengba.com
keontech.net
kepard.com
keycdn.com
khatrimaza.org
kichiku-doujinko.com
killwall.com
kingstone.com.tw
kk-whys.co.jp
kodingen.com
kompozer.net
koolsolutions.com
koornk.com
koranmandarin.com
ktzhk.com
kurtmunger.com
kusos.com
kwcg.ca
kzeng.info
labiennale.org
lamnia.co.uk
laogai.org
laptoplockdown.com
laqingdan.net
larsgeorge.com
lastfm.es
leafyvpn.net
left21.hk
legaltech.law.com
leisurepro.com
lematin.ch
lenwhite.com
lerosua.org
lesoir.be
letscorp.net
le-vpn.com
liangyou.net
liaowangxizang.net
liberal.org.hk
like.com
line.me
lingvodics.com
linux.org.hk
listentoyoutube.com
liudejun.com
liujianshu.com
liuxiaotong.com
liveleak.com
livestream.com
livevideo.com
livingonline.us
livingstream.com
localdomain.ws
lockdown.com
lockestek.com
lofi.e-hentai.org
logiqx.com
logmike.com
longtermly.net
longtoes.com
lookingglasstheatre.org
lookpic.com
lovetvshow.com
lpsg.com
lrfz.com
lrip.org
lsd.org.hk
lsm.org
lsmchinese.org
lsmkorean.org
lupm.org
lushstories.com
lvhai.org
lvv2.com
m.plixi.com
macgamestore.com
mad-ar.ch
madonna-av.com
madthumbs.com
magazines.sina.com.tw
magic-net.info
makemymood.com
mangafox.com
mangafox.me
marc.info
martau.com
martincartoons.com
marxist.net
matainja.com
mathable.io
mathiew-badimon.com
matome-plus.com
matome-plus.net
matsushimakaede.com
mattwilcox.net
mcadforums.com
md-t.org
mediachinese.com
mediafreakcity.com
medium.com
meetup.com
megaproxy.com
megarotic.com
megurineluka.com
melon-peach.com
memehk.com
messenger.com
metarthunter.com
meteorshowersonline.com
metrolife.ca
mfxmedia.com
mgoon.com
mgstage.com
mh4u.org
michaelmarketl.com
mike.cz.cc
minghui.org
mingjinglishi.com
mingjingtimes.com
minzhuhua.net
miroguide.com
mixero.com
mixx.com
mizzmona.com
mmaaxx.com
mobatek.net
mobileways.de
moeerolibrary.com
mog.com
mondex.org
monitorchina.org
monster.com
moodyz.com
moonbbs.com
morningsun.org
moroneta.com
movements.org
moviefap.com
mpettis.com
mrtweet.com
mthruf.com
mtw.tl
mullvad.net
multiply.com
muzi.com
muzi.net
muzu.tv
mvg.jp
mx981.com
myaudiocast.com
mychinamyhome.com
mychinanews.com
mycnnews.com
myeclipseide.com
myforum.com.hk
myforum.com.uk
mykomica.org
mymusic.net.tw
myparagliding.com
mypopescu.com
my-private-network.co.uk
naacoalition.org
naitik.net
nakido.com
nalandabodhi.org
nalandawest.org
namsisi.com
nanyang.com
nanyangpost.com
national-lottery.co.uk
nationwide.com
naughtyamerica.com
navyfamily.navy.mil
navyreserve.navy.mil
ncn.org
nekoslovakia.net
netflix.com
netme.cc
newchen.com
newsancai.com
newscn.org
newsminer.com
newstamago.com
newstapa.org
newtalk.tw
nexon.com
nexton-net.jp
nf.id.au
nga.mil
nic.cz.cc
nic.google
nighost.org
ninjaproxy.ninja
niusnews.com
njactb.org
njuice.com
nko.navy.mil
nobel.se
nobodycanstop.us
nokogiri.org
nokola.com
nordstrom.com
nordstromimage.com
nordstromrack.com
nordvpn.com
nottinghampost.com
novelasia.com
nownews.com
noypf.com
npa.go.jp
nrk.no
nsc.gov.tw
ntbna.gov.tw
ntd.tv
ntdtv.cz
ntsna.gov.tw
nuexpo.com
nurgo-software.com
nusatrip.com
nuuvem.com
nyaa.eu
nyaa.se
nytco.com
nytimes.com
nytimg.com
nzchinese.net.nz
october-review.org
oculus.com
ogaoga.org
okayfreedom.com
olumpo.com
omni7.jp
omnitalk.com
omnitalk.org
on.cc
on2.com
onedrive.live.com
onlineyoutube.com
ontrac.com
opendemocracy.net
openid.net
openleaks.org
openvpn.net
openwebster.com
orientaldaily.com.my
orient-doll.com
orn.jp
orzistic.org
osfoora.com
otnd.org
otto.de
ourdearamy.com
ourtv.hk
overplay.net
oversea.istarshine.com
ow.ly
pachosting.com
pacopacomama.com
pagodabox.com
panacom.co.jp
pandora.com
panluan.net
panoramio.com
pao-pao.net
parkansky.com
passion.com
pastie.org
pbworks.com
pbxes.com
pbxes.org
pct.org.tw
pdproxy.com
pds.nasa.gov
peace.ca
pekingduck.org
pen.io
penchinese.net
peoplenews.tw
peopo.org
phncdn.com
phosphation13.rssing.com
photodharma.net
photofocus.com
phuquocservices.com
picasaweb.com
pin6.com
ping.fm
pinoy-n.com
pixelqi.com
pixnet.net
placemix.com
playboy.com
playboyplus.com
playno1.com
playpcesor.com
po2b.com
podictionary.com
polymer-project.org
popvote.hk
popyard.org
pornhd.com
pornmm.net
pornrapidshare.com
pornstarclub.com
porntvblog.com
poskotanews.com
power.com
powercx.com
prayforchina.net
premeforwindows7.com
presentationzen.com
prestige-av.com
pritunl.com
privacybox.de
privateinternetaccess.com
privatepaste.com
privatetunnel.com
privatevpn.com
procopytips.com
prosiben.de
proxfree.com
proxomitron.info
proxpn.com
proxylist.org.uk
proxynetwork.org.uk
proxypy.net
proyectoclubes.com
psblog.name
psiphon.ca
psiphon3.com
pts.org.tw
ptt.cc
pullfolio.com
pure18.com
pureconcepts.net
pureinsight.org
purepdf.com
purevpn.com
putty.org
puttycm.free.fr
qanote.com
qienkuen.org
qiwen.lu
qoos.com
qq.co.za
qstatus.com
qtrac.eu
qtweeter.com
questvisual.com
quitccp.net
quitccp.org
r18.com
radiohilight.net
radiovaticana.org
radiovncr.com
rael.org
raggedbanner.com
raidcall.com.tw
ranyunfei.com
rapidmoviez.com
rapidvpn.com
razyboard.com
rd.com
rdio.com
readingtimes.com.tw
readmoo.com
recaptcha.net
recoveryversion.com.tw
redhotlabs.com
referer.us
reflectivecode.com
registry.google
renyurenquan.org
retweeteffect.com
retweetrank.com
rferl.org
rfi.fr
rlwlw.com
robustnessiskey.com
rocket-inc.net
rocmp.org
roc-taiwan.org
rojo.com
rolia.net
ronjoneswriter.com
rsf.org
rsf-chinese.org
rssmeme.com
rtalabel.org
s1heng.com
s8forum.com
sacom.hk
sadistic-v.com
sadpanda.us
safervpn.com
saiq.me
sakuralive.com
salvation.org.hk
savetibet.org
say2.info
scihub.org
scramble.io
scriptspot.com
s-cute.com
search.aol.com
secretgarden.no
secretsline.biz
secure.logmein.com
securetunnel.com
seevpn.com
seezone.net
sesawe.net
sethwklein.net
sevenload.com
sex3.com
sex8.cc
sexinsex.net
sfshibao.com
sftuk.org
shadowsocks.org
shangfang.org
sharecool.org
sharpdaily.com.hk
shellfire.de
shenyunperformingarts.org
shenzhoufilm.com
sherabgyaltsen.com
shixiao.org
shizhao.org
shodanhq.com
shutterstock.com
sidelinesnews.com
simplecd.org
singaporepools.com.sg
singtao.com
sinoants.com
sinocast.com
sis001.com
site90.net
sitekreator.com
siteks.uk.to
sitemaps.org
sjum.cn
sketchappsources.com
skimtube.com
skybet.com
skyvegas.com
slacker.com
slavasoft.com
slheng.com
slickvpn.com
snapchat.com
snaptu.com
sndcdn.com
snooper.co.uk
sobees.com
soc.mil
sockslist.net
softether.org
softether-download.com
softwarebychuck.com
so-ga.net
sogclub.com
sogrady.me
soh.tw
sohcradio.com
sohfrance.org
solarsystem.nasa.gov
somee.com
so-news.com
songjianjun.com
sorting-algorithms.com
sos.org
soulcaliburhentai.net
soundcloud.com
soundofhope.org
soup.io
soupofmedia.com
space-scape.com
spankbang.com
spb.com
speakerdeck.com
spencertipping.com
spicevpn.com
sports.williamhill.com
spotflux.com
spotify.com
springboardplatform.com
sprite.org
sproutcore.com
sproxy.info
ssh91.com
sstmlt.net
stage64.hk
standupfortibet.org
starp2p.com
startpage.com
static.comico.tw
static-economist.com
staticflickr.com
statueofdemocracy.org
stc.com.sa
steel-storm.com
stephaniered.com
sthoo.com
stoneip.info
stoptibetcrisis.net
storagenewsletter.com
storify.com
storm.mg
stoweboyd.com
streamingthe.net
strongvpn.com
studentsforafreetibet.org
stumbleupon.com
sugarsync.com
suissl.com
sumrando.com
sunmedia.ca
sunporno.com
superpages.com
supervpn.net
surfeasy.com
surrenderat20.net
svwind.com
swagbucks.com
sweux.com
swift-tools.net
swissvpn.net
switch1.jp
switchvpn.net
syncback.com
synergyse.com
sysadmin1138.net
szetowah.org.hk
t.co
t.orzdream.com
t66y.com
t88.ca
taaze.tw
tacc.cwb.gov.tw
taedp.org.tw
tafaward.com
tagwalk.com
taipeisociety.org
taiwandaily.net
taiwanembassy.org
taiwanncf.org.tw
taiwannews.com.tw
taiwantoday.tw
taiwantt.org.tw
talkboxapp.com
talkonly.net
tamiaode.tk
tanc.org
taolun.info
tapanwap.com
target.com
taup.net
taweet.com
tbcollege.org
tbpic.info
tbsec.org
tbsn.org
techlifeweb.com
teck.in
telegram.org
telegraph.co.uk
tensorflow.org
theatrum-belli.com
thebcomplex.com
thebobs.com
thebodyshop-usa.com
thedw.us
thehun.net
theinitium.com
thelifeyoucansave.com
thestandnews.com
thetibetpost.com
thewgo.org
thinkwithgoogle.com
thomasbernhard.org
throughnightsfire.com
thywords.com
tiananmenduizhi.com
tiananmenuniv.com
tiananmenuniv.net
tiandixing.org
tianti.io
tibet.com
tibet.net
tibet.org
tibetaction.net
tibetanliberation.org
tibetanyouthcongress.org
tibet-envoy.eu
tibetgermany.de
tibethouse.us
tibetnetwork.org
tibetonline.com
tibetonline.tv
tibetsociety.com
tibetwrites.org
tiltbrush.com
tinypaste.com
tkcs-collins.com
tma.co.jp
tmagazine.com
tnaflix.com
tokyocn.com
tokyo-porn-tube.com
to-porno.com
topshare.us
topsy.com
toptip.ca
torguard.net
torproject.org
torrentcrazy.com
torrentprivacy.com
torrentproject.se
torrenty.org
torrentz.eu
torvpn.com
totalvpn.com
toutfr.com
tpi.org.tw
transgressionism.org
transparency.org
travelinlocal.com
treemall.com.tw
trendsmap.com
trialofccp.org
tripod.com
trustedbi.com
truthcn.com
tsdr.uspto.gov
tt1069.com
tt-rss.org
tttan.com
tube8.com
tube911.com
tubewolf.com
tumblr.com
tunnelbear.com
tuo8.org
turbohide.com
turbotwitter.com
turningtorso.com
turntable.fm
tuvpn.com
tuxtraining.com
tv-intros.com
tvunetworks.com
tw.jiepang.com
tw.knowledge.yahoo.com
tw.mobi.yahoo.com
tw.news.yahoo.com
twapperkeeper.com
twaud.io
twblogger.com
tweepguide.com
tweeplike.me
tweepml.org
tweetbackup.com
tweetboard.com
tweetboner.biz
tweetdeck.com
tweetedtimes.com
tweetmylast.fm
tweetphoto.com
tweetrans.com
tweetree.com
tweettunnel.com
tweetwally.com
twerkingbutt.com
twftp.org
twibble.de
twibs.com
twiffo.com
twiggit.org
twimg.com
twindexx.com
twip.me
twipple.jp
twishort.com
twister.net.co
twisterio.com
twit2d.com
twitcause.com
twitgether.com
twitiq.com
twitlonger.com
twitoaster.com
twitonmsn.com
twitpic.com
twitstat.com
twitter.com
twitter.jp
twitter4j.org
twittercounter.com
twittergadget.com
twitterkr.com
twittermail.com
twitterrific.com
twittertim.es
twitturk.com
twitturly.com
twitvid.com
twstar.net
twttr.com
twyac.org
tycool.com
typepad.com
tzangms.com
uberproxy.net
ucdc1998.org
uc-japan.org
uderzo.it
udn.com
uforadio.com.tw
uhdwallpapers.org
uhrp.org
uighur.nl
ukliferadio.co.uk
ultravpn.fr
unblock.cn.com
unblocksit.es
unblock-us.com
underwoodammo.com
unholyknight.com
unknownspace.org
uocn.org
uproxy.org
urbansurvival.com
urlborg.com
urlparser.com
usacn.com
usaip.eu
usfk.mil
usma.edu
usmc.mil
usno.navy.mil
ustream.tv
utopianpal.com
uvwxyz.xyz
uyghuramerican.org
uyghurcongress.org
vatn.org
vcfbuilder.org
vcf-online.org
vegas.williamhill.com
vegasred.com
ventureswell.com
versavpn.com
verybs.com
vevo.com
viber.com
vid.me
vidble.com
video.aol.com
videobam.com
videomega.tv
viki.com
vimeo.com
vimperator.org
vincnd.com
vinniev.com
viu.com
vivthomas.com
vmixcore.com
voacantonese.com
voachinese.com
voachineseblog.com
voatibetan.com
voatibetanenglish.com
vot.org
voxer.com
vpn.cjb.net
vpnforgame.net
vpngate.jp
vpngate.net
vpninja.net
vpnmaster.com
vpnpick.com
vpnpop.com
vpnpronet.com
vpnreactor.com
vpnreviewz.com
vpnsecure.me
vpntunnel.com
vpnuk.info
vpnvip.com
vporn.com
vtunnel.com
vuku.cc
w.org
waffle1999.com
wallpapercasa.com
waltermartin.com
waltermartin.org
wanderinghorse.net
wangafu.net
wangjinbo.org
wango.org
wanz-factory.com
warbler.iconfactory.net
waselpro.com
watchmygf.net
wattpad.com
wav.tv
waveprotocol.org
wearn.com
web2project.net
webmproject.org
webrtc.org
wefightcensorship.org
weiming.info
wengewang.org
wenyunchao.com
westca.com
westernwolves.com
westpoint.edu
wexiaobo.org
wezone.net
wforum.com/
whatblocked.com
whatbrowser.org
wheelockslatin.com
whereiswerner.com
wheretowatch.com
whyx.org
wiki.jqueryui.com
wiki.oauth.net
wiki.phonegap.com
wikileaks.ch
wikileaks.de
wikileaks.eu
wikileaks.lu
wikileaks.org
wikileaks.pl
wikimapia.org
wikiwiki.jp
willw.net
windowsphoneme.com
wingamestore.com
wiredbytes.com
wiredpen.com
wireshark.org
wisevid.com
withgoogle.com
wizcrafts.net
wjbk.org
wlx.sowiki.net
woeser.com
wolfax.com
woopie.jp
woopie.tv
workatruna.com
workersthebig.net
worldvpn.net
wowlegacy.ml
wp.com
wpoforum.com
wqyd.org
wsj.com
wufafangwen.com
wuguoguang.com
wujieliulan.com
wwitv.com
www.ajsands.com
www.klip.me
www.linksalpha.com
www.moztw.org
www.powerpointninja.com
www.vpncup.com
www.wan-press.org
x-art.com
xbabe.com
x-berry.com
xbookcn.com
xcafe.in
xcity.jp
xfinity.com
xiaohexie.com
xiaolan.me
xiaoma.org
xinmiao.com.hk
xjp.cc
xjtravelguide.com
xlfmwz.info
xml-training-guide.com
xn--4gq171p.com
xn--p8j9a0d9c9a.xn--q9jyb4c
xnxx.com
xpud.org
xskywalker.com
xtube.com
xuchao.net
xuchao.org
xvideos.es
x-wall.org
xxx.com
xxxx.com.au
yahoo.com.hk
yakbutterblues.com
yam.com
yam.org.tw
yasni.co.uk
yasukuni.or.jp
yeahteentube.com
yecl.net
yeelou.com
yegle.net
yes123.com.tw
yesasia.com
yesasia.com.hk
yhcw.net
yidio.com
yipub.com
yogichen.org
youjizz.com
youpai.org
youporn.com
youporngay.com
yourepeat.com
yourprivatevpn.com
yousendit.com
youtu.be
youtube.com
youtube-nocookie.com
youversion.com
youxu.info
ytimg.com
yunchao.net
yvesgeleyn.com
yyii.org
zannel.com
zaobao.com.sg
zarias.com
zattoo.com
zdnet.com.tw
zello.com
zeutch.com
zhanbin.net
zhangtianliang.com
zhao.1984.city
zhenlibu.info
zhongguotese.net
zhongmeng.org
zhreader.com
zhuatieba.com
zhuichaguoji.org
zillionk.com
zinio.com
ziplib.com
zkaip.com
zmw.cn
zonaeuropa.com
zonghexinwen.com
zootool.com
zozotown.com
zuo.la
zuobiao.me
zuola.com
zvereff.com
zynamics.com
